# Generated by Django 2.2.28 on 2026-03-25 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20260325_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 3, 25, 20, 28, 39, 306780), verbose_name='Дата и время публикации'),
        ),
    ]
