# Generated by Django 2.2.28 on 2026-03-26 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20260325_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 3, 26, 12, 27, 10, 14680), verbose_name='Дата и время публикации'),
        ),
    ]
