# Generated by Django 2.2.28 on 2026-04-19 18:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20260417_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория каталога',
                'verbose_name_plural': 'Категории каталога',
                'db_table': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 19, 21, 4, 29, 232470), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 19, 21, 4, 29, 233471), verbose_name='Дата и время оставления комментария'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('short_desc', models.CharField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('full_desc', models.TextField(verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Цена должна быть положительным числом')], verbose_name='Цена')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент каталога',
                'verbose_name_plural': 'Элементы каталога',
                'db_table': 'Products',
                'ordering': ['title'],
            },
        ),
    ]
