# Generated by Django 2.2.28 on 2026-04-19 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20260419_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 19, 21, 13, 7, 84529), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 19, 21, 13, 7, 85534), verbose_name='Дата и время оставления комментария'),
        ),
    ]
