# Generated by Django 2.2.28 on 2026-04-20 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20260419_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 21, 0, 48, 1, 467688), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 21, 0, 48, 1, 468680), verbose_name='Дата и время оставления комментария'),
        ),
    ]
