# Generated by Django 2.2.28 on 2026-04-20 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20260421_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 21, 0, 52, 27, 440216), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 21, 0, 52, 27, 441214), verbose_name='Дата и время оставления комментария'),
        ),
    ]
